name: Test Workflow
on:
  push:
    branches:
    - pre-deployment
    paths:
    - .github/workflows/**
  workflow_dispatch:
jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        ref: ${{ github.sha }}
        path: src
